// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SvnDetectorController from "./svn_detector_controller"
application.register("svn-detector", SvnDetectorController)

import LayoutConfigController from "./layout_config_controller"
application.register("layout-config", LayoutConfigController)

import RepositorySubscriptionController from "./repository_subscription_controller"
application.register("repository-subscription", RepositorySubscriptionController)